### PR TITLE
feat: Open external links on navto

### PR DESCRIPTION
**Pull request by jonas-martinez**
Closes #

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [x] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by jonas-martinez** [comment]
`Uncaught MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)`

**Comment by jonas-martinez** [comment]
https://stackoverflow.com/questions/50459272/missingpluginexception-while-using-plugin-for-flutter

**Comment by jonas-martinez** [comment]
It seems to work now, I needed to run a `flutter clean` before the `flutter build web`. Apparently this is a known issue on Flutter and this is the fix.

**Review by taorepoara — APPROVED** [review]
Seems OK

**Comment by taorepoara** [comment]
I'll test it this afternoon

**Pull request merged**
